sudo: required
language: c
services:
  - docker

script:
  - make bootstrap
  - make lint
  - make test
  - make build

deploy:
  provider: script
  script: bash scripts/install.sh && bash scripts/deploy.sh
  on:
    branch: infra-testing
