version: "3.4"

services:
  graphql-schema:
    build:
      context: .
      dockerfile: ./packages/graphql-schema/Dockerfile
      target: development
    volumes:
      - ./packages/graphql-schema/src:/app/packages/graphql-schema/src
      - ./packages/graphql-schema/tests:/app/packages/graphql-schema/tests
      # - ./packages/graphql-schema/typings:/app/packages/graphql-schema/typings
      - ./packages/graphql-schema/package.json:/app/packages/graphql-schema/package.json
      - ./packages/graphql-schema/tsconfig.json:/app/packages/graphql-schema/tsconfig.json
      - ./packages/graphql-schema/tslint.json:/app/packages/graphql-schema/tslint.json

      # Required workspace root files. Delegated for performance.
      - ./.prettierrc:/app/.prettierrc:delegated
      - ./tsconfig.json:/app/tsconfig.json:delegated

      # Required linked packages and workspace files. Delegated for performance.
      - ./packages/melon.js/lib:/app/packages/melon.js/lib:delegated
      - ./packages/melon.js/package.json:/app/packages/melon.js/package.json:delegated

  graphql-server:
    build:
      context: .
      dockerfile: ./packages/graphql-server/Dockerfile
      target: development
    volumes:
      - ./packages/graphql-server/src:/app/packages/graphql-server/src
      - ./packages/graphql-server/tests:/app/packages/graphql-server/tests
      - ./packages/graphql-server/typings:/app/packages/graphql-server/typings
      - ./packages/graphql-server/package.json:/app/packages/graphql-server/package.json
      - ./packages/graphql-server/tsconfig.json:/app/packages/graphql-server/tsconfig.json
      - ./packages/graphql-server/tsconfig.build.json:/app/packages/graphql-server/tsconfig.build.json
      - ./packages/graphql-server/tslint.json:/app/packages/graphql-server/tslint.json
      - ./packages/graphql-server/backpack.config.js:/app/packages/graphql-server/backpack.config.js
      - ./packages/graphql-server/.env.defaults:/app/packages/graphql-server/.env.defaults
      # - ./packages/graphql-server/.env:/app/packages/graphql-server/.env

      # Required linked packages and workspace files. Delegated for performance.
      - ./packages/melon.js/lib:/app/packages/melon.js/lib:delegated
      - ./packages/melon.js/package.json:/app/packages/melon.js/package.json:delegated
      - ./packages/melon.js/.babelrc:/app/packages/melon.js/.babelrc:delegated
      - ./packages/graphql-schema/src:/app/packages/graphql-schema/src:delegated
      - ./packages/graphql-schema/package.json:/app/packages/graphql-schema/package.json:delegated
      - ./packages/exchange-aggregator/src:/app/packages/exchange-aggregator/src:delegated
      - ./packages/exchange-aggregator/package.json:/app/packages/exchange-aggregator/package.json:delegated

      # Required workspace root files. Delegated for performance.
      - ./.prettierrc:/app/.prettierrc:delegated
      - ./tsconfig.json:/app/tsconfig.json:delegated
    ports:
      - "3030:3030"
    networks:
      - melonproject

  manager-interface:
    build:
      context: .
      dockerfile: ./packages/manager-interface/Dockerfile
      target: development
    volumes:
      - ./packages/manager-interface/src:/app/packages/manager-interface/src
      - ./packages/manager-interface/config:/app/packages/manager-interface/config
      - ./packages/manager-interface/tests:/app/packages/manager-interface/tests
      # - ./packages/manager-interface/typings:/app/packages/manager-interface/typings
      - ./packages/manager-interface/package.json:/app/packages/manager-interface/package.json
      - ./packages/manager-interface/tsconfig.json:/app/packages/manager-interface/tsconfig.json
      - ./packages/manager-interface/tslint.json:/app/packages/manager-interface/tslint.json
      - ./packages/manager-interface/next.config.js:/app/packages/manager-interface/next.config.js
      - ./packages/manager-interface/.env.defaults:/app/packages/manager-interface/.env.defaults
      # - ./packages/manager-interface/.env:/app/packages/manager-interface/.env

      # Required linked packages. Delegated for performance.
      - ./packages/melon.js/lib:/app/packages/melon.js/lib:delegated
      - ./packages/melon.js/package.json:/app/packages/melon.js/package.json:delegated
      - ./packages/graphql-schema/src:/app/packages/graphql-schema/src:delegated
      - ./packages/graphql-schema/package.json:/app/packages/graphql-schema/package.json:delegated
      - ./packages/manager-components/src:/app/packages/manager-components/src:delegated
      - ./packages/manager-components/package.json:/app/packages/manager-components/package.json:delegated
      - ./packages/exchange-aggregator/src:/app/packages/exchange-aggregator/src:delegated
      - ./packages/exchange-aggregator/package.json:/app/packages/exchange-aggregator/package.json:delegated

      # Required workspace root files. Delegated for performance.
      - ./.prettierrc:/app/.prettierrc:delegated
      - ./tsconfig.json:/app/tsconfig.json:delegated
    ports:
      - "3000:3000"
    networks:
      - melonproject

  manager-components:
    build:
      context: .
      dockerfile: ./packages/manager-components/Dockerfile
      target: development
    volumes:
      - ./packages/manager-components/src:/app/packages/manager-components/src
      - ./packages/manager-components/config:/app/packages/manager-components/config
      - ./packages/manager-components/tests:/app/packages/manager-components/tests
      # - ./packages/manager-components/typings:/app/packages/manager-components/typings
      - ./packages/manager-components/package.json:/app/packages/manager-components/package.json
      - ./packages/manager-components/tsconfig.json:/app/packages/manager-components/tsconfig.json
      - ./packages/manager-components/tslint.json:/app/packages/manager-components/tslint.json

      # Required workspace root files. Delegated for performance.
      - ./.prettierrc:/app/.prettierrc:delegated
      - ./tsconfig.json:/app/tsconfig.json:delegated
    ports:
      - "3060:3060"
    networks:
      - melonproject

networks:
  melonproject:
    external: true
